#' @title phyloseq.normalize
#' @description
#' Normalize palm_id coverage "counts". Currently only implements Coverage Per Million (comparable to reads per million). Expects phyloseq object with format and metadata generated by phyloseq.palmid function.
#' @param dat phyloseq object generated from phyloseq.palmid
#' @param method Normalization method, character string. Currently only accepts "cpm" (Counts Per Million).
#' @return phyloseq object with normalized coverage
#' @seealso [phyloseq.palmid()]
#' @import tidyverse
#' @import phyloseq
#' @export 



phyloseq.normalize <- function(dat, 
                               method = "cpm"){
  
  # normalize
  cpm.size.factor <- (dat %>% sample_data() %>% data.frame %>% pull(spots))/1E6 # library size factor 
  norm <- (dat %>% t %>% otu_table/cpm.size.factor) %>% t()                     # normalized otu table 
  
  # update phyloseq
  out <- dat
  otu_table(out) <- norm
  
  return(out)
}